server:
  port: 8085
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pcms?serverTimezone=GMT%2B8
    username: root
    password: root
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
# MyBatis ??
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.code.privateclinic.bean
  configuration:
    map-underscore-to-camel-case: true


jwt:
  expiration: 7200
  secret1: mySecretKey1234567890abcdefghijklmnopqrstuvwxyz
  secret2: qwertyuioplkjhgfdsazxcvbnm1092837456mySecretKey
